trigger:
  - main
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
  - job: Job_1
    displayName: Windows 2019 agent job
    pool:
      vmImage: windows-2019
    steps:
      - task: CopyFiles@2
        displayName: "Copy files"
        inputs:
          Contents: |
            **
            !.git/**/*
            !.gitignore
            !README.md
            !build-pipeline.yml
            !security-pipeline.yml
          TargetFolder: "$(build.artifactstagingdirectory)"
      - task: PublishBuildArtifacts@1
        displayName: "Publish artifact"
        inputs:
          PathtoPublish: "$(build.artifactstagingdirectory)"
          ArtifactName: "Drop"
    condition: succeededOrFailed()
