apiVersion: 1

datasources:
  - name: 'DevOps'
    type: 'grafana-azure-monitor-datasource'
    access: 'proxy'
    jsonData:
      azureAuthType: clientsecret
      cloudName: azuremonitor
      # greenflux.com
      tenantId: 3145cea7-e759-4aeb-b8fc-506e0a02fd91
      # the grafana AAD app registration
      clientId: b26952df-d613-426f-a817-74c49f82b9a7
      # GFX PROD (csp)
      subscriptionId: 58d729f3-33af-4981-84ca-93e537fbdfbc
    secureJsonData:
      # it's a secret from the grafana AAD app registration
      # see https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/Credentials/appId/b26952df-d613-426f-a817-74c49f82b9a7/isMSAApp/
      clientSecret: $(grafanaAppRegistrationSecret)
    isDefault: true
    version: 1
    editable: true
